
levellocks = [0,1,1,1,1,1,1,1,1,1,1,1]




level1 = {"num":1,"map":
 [
  "                                                                                                                      ",
  "                                                                                                                      ",
  "                                                                                                                      ",
  "              c                                   c c                                             gggggggggggggggggg  ",
  "g            c c                                a     c                                           gggggggggggggggggg  ",
  "g           c   c                             rgggg    c                                    f     gggggggggggggggggg  ",
  "g          ggg ggg         c  c  c  c       rgggggg    c       gg   gg  gg  gg                    gggggggggggggggggg  ",
  "g  P                 g  Ct     t         gggggggggg   t  T                            T           gggggggggggggggggg  ",
  "gggggggggggg     ggggggggggggggggggggggggggggggggggggggggggggggSSSSSSSSSSSSSSSSggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggSSSSSggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"beach.png",
  "background image":"beachbackground.png",
         "music":"beachtheme.ogg",
          "decor":["palmtree1.png","palmtree2.png","beachbush.png"]}
level2 = {"num":2,"map":
 ["                                                                                                                      ",
  "gg                                                 cccccc                                                           gg",
  "gg             ggg                                gbbbbbbg                                                          gg",
  "gg           bbgggbb                              c  c c  c                                                         gg",
  "gg             ggg                              gbbbbbbbbbbg                                                       hgg",
  "gg           bbgggbbbbbbbbbbggl                                                                                     gg",
  "gg P           ggg          ggggl             gbbbbbbbbbbbbbbbg                       t       T     t  f         bbbgg",
  "ggl    t      rggg c c Cc  pgggggggl  t  T                        t                   g   aC  g  aC g               gg",
  "ggggggggggggggggggggggggggggggggggggggggggggggSSSSSSSSSSSSSSSSSggggggl      C     rggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"beach.png",
  "background image":"beachbackground.png",
         "music":"beachtheme.ogg",
          "decor":["palmtree1.png","palmtree2.png","beachbush.png"] }
level3 = {"num":3,"map":
 [
  "                                                                                                                      ",
  "g                                                                                            ggg                   ggg",
  "g                          ggS c  Sgg                                                       gggg                   ggg",
  "g                        bbggS  c Sggh                    cc        cc                     ggggg               f   ggg",
  "g           c   c    c     ggS c  Sggg t                                                  gggggg                   ggg",
  "g                       bbbggS  c Sggggggg         g Ct  g   gC T  g   g  t Cg           ggggggg             bbbbbbggg",
  "g           g   g    g     ggS         gggbbbb     ggggggg   ggggggg   ggggggg          gggggggg                   ggg",
  "gg  P   g  C  a C  a  C   gggS                p                                        ggggggggg         p    a a aggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSggggggggggggggSSSSSSgggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"beach.png",
  "background image":"beachbackground.png",
         "music":"beachtheme.ogg",
          "decor":["palmtree1.png","palmtree2.png","beachbush.png"] }

level4 = {"num":4,"map":
 ["                                                                                                                      ",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                f        cc  cc  cc                 g",
  "g                                                                                        c  cc  cc  cc               g",
  "g                                                                                      T   a  a  a  a  T        bbbbbg",
  "g                                       c h cccccccccc T    c                   ggggggggggggggggggggggggggggg        g",
  "g                                      c  ggggggggggggggggbbg c                       gggggggggggggggggggg        bb g",
  "g                                     c   gggggggggggggggg  g  c                          ggggggggggggg              g",
  "g                     B               c   ggggggggggggggggbbg  c                             ggggggg            bbbbbg",
  "g                                     c   gggggggggg  ccccccg  c                                                     g",
  "g              g              g       c   gggggggggg  ggggggg                     gbbbbbbbbb        B          bbbbbbg",
  "g            rggbbbbbbbbbbbbbbggl         gggg       ggggggggggggggggggg         gg                                  g",
  "g           rggg              gggl        gggg    gggggggggggggggggggggg        ggg                              bbbbg",
  "g P   t    rggggp   cc D cc   ggggl   a a aDa a a ggggggggggghcccccc           gggg      a  D        a               g",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"grassland_ground.png",
  "background image":"grasslandbg.png",
   "music":"grasslandtheme.ogg",
          "decor":["oaktree1.png","oaktree2.png","bush.png"]}

level5 = {"num":5,"map":
 ["                                                                                                                      ",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                  h g",
  "g                  B                                                                            g     f        bbbbbbg",
  "g                            B                                                                  g                    g",
  "gS           h ctc cTc Bc c c                    bSgSc Sgg                                      ggggggggbbbbb        g",
  "gS          ggggggggggggggggggbbbbbbbbbbbbggS   b SgS cSgg                                      gggggggg             g",
  "gS          gggggggggggggggggg            ggS  b  SgS  Sgg                                            gg      bbbbbbbg",
  "gS          ggggggggggggggSSSS                b   SgS cSgg                                            gg             g",
  "gS          gggggSSSSSSSSS                   b    SgSc Sggbbbggl                                      ggbbbbb        g",
  "gS          SSSSS                                  g         gggl                                                    g",
  "gS                          ggbbb   bbb  bb  bbggggg      bbbggggl   cc  cc  cc  cc      Sgg                   bbbbbbg",
  "gS                  gggggggggg                 ggggg         gggggl                   Sgg gg                         g",
  "gS   P      ggggggggggggggggggSSSSSSSSSSSSSSSSggggggSSSggggggggggggggSSggSSggSSggSSggg ggggg   T      p           a  g",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"grassland_ground.png",
  "background image":"grasslandbg.png",
   "music":"grasslandtheme.ogg",
          "decor":["oaktree1.png","oaktree2.png","bush.png"]}

level6 = {"num":6,"map":
 ["                                                                                                                      ",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                                                                                                                    g",
  "g                              BhB                                                                                   g",
  "g                                      p      T                                                                      g",
  "g                              gggggggggggggggggb            a                                                       g",
  "g                                               b          gggg                                                      g",
  "g                                               b          gggg B                                                    g",
  "g                                               b          gggg                         rggbbbbbbbbbbbgggg           g",
  "ga    P t    Dg             B        B          ggggggggggggggg   gg                   rggg    cccc   gggg           g",
  "ggggggggggggggg    D  gSSgSSgSSgSSgSSgSSgD      ggggggggggggggg        ggl     a  T   rggggSSSSgh gSSSgggggg  p    aag",
  "ggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggSSSSSSSSgggggggggggggggggggggggggggggggggg     gggggggg",
  "gggggg                       c  cc  c  cc  c                cSSggggggggSSc                  c c c             gggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggg                          gggggggggggggggggggggggggggSSSgggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"grassland_ground.png",
  "background image":"grasslandbg.png",
   "music":"grasslandtheme.ogg",
          "decor":["oaktree1.png","oaktree2.png","bush.png"]}

level7 = {"num":7 ,"map":
 ["gg                                                                                                                                  ",
  "gg                                                                                                                                  ",
  "gg P                                                                                                                                ",
  "ggl                                                                                                                                 ",
  "gggg                                                                    cc  cc                                                      ",
  "ggggl                                                                  c  cc  c                                                     ",
  "gggggl                                                                                c                                            g",
  "ggggggl               8   t                                            bbbbbbbbbbb     c                                           g",
  "gggggggl           ggggbbbg                                                                                                       lg",
  "ggggggggl          gggg c gg                                        SS  b            bbbbbbb                                      gg",
  "gggggggggl    c    ggggbbbggg        ccc     ccc                   SggS      b   S            c                                   gg",
  "gggggggggggl  c   ggggg c gggg                                     SggS         SGS            c                                  gg",
  "ggggggggggggg c gggggggbbbgggg     g  T Qg  g  tQg                  SSSS     b   S          bbbbb                                 gg",
  "ggggggggggggg c ggggggg c ggggbb   ggggggg  gggggg  g  g             SggS b    SS         c                                   8   gg",
  "ggggggggggggg c gggggggbbbgggg                           ggg         SggS     SggS       c                    f         ggggggg   gg",
  "gggg          c           gggg                           ggggg        SS    b SggS                                          cccchggg",
  "gggg          c        gggggggSSSSSSSSSSSSSSSSSSSSSSSSSSSgggggggg              SSh  T      a      Q  a    Q    a    Q     Q  ccccggg",
  "gggg   Q      p        ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"snowy_ground.png",
  "background image":"snowbg.png",
   "music":"icetheme.ogg",
          "decor":["pinetree1.png","pinetree2.png","snowbush.png"]}

level8 = {"num":8 ,"map":
 ["                                                                                                                                                ",
  "                                                                                                                                                ",
  "                                                                                                                                              gg",
  "                                                                                       cccc                                               gggggg",
  "                                                                                                                                       ggggggggg",
  "                                                                              T 8  gggggSSggggg   t                                  ggggggggggg",
  "                             8               g  8  g                   T   gggggggggggggggggggggggggg    T                        gggggggggggggg",
  "                          ggggggg   c        ggggggg                  gggggggggggggggggggggggggggggggggggggg   t                gggggggggggggggg",
  "                         ggggggggg     c                           gggggggggggg                  ggggggggggggggggg             ggggggggg    gggg",
  "                      g  gggggggggg  c                          ggggggggggg                             gggggggggggggg         gggggggg      ggg",
  "                     gg  ggggggggggg                          gggggggggg              8     S    8             gggggggggggg    gggg           gg",
  "                    ggg hgggggggggggg     T      Q  t       gggggggggg              ggggg  SgS ggggg                     gg    ggggg          gg",
  "g            T     gggg  gggggggggggggggggggggggggggggggggggggggg                           S                            gg                    g",
  "g           ggg  gggggg  gggggggggggggggggg   ggg   ggg    gggggg                      c c c c c c c                     gg             f     hg",
  "g          ggggccgggggg  ggg              S    S     S     S                     c c      ggggg     c c                                        g",
  "gP        gggggccgggggg  ggg                cc   ccc    cc                            ggggggggggggg                                            g",
  "gg       gggggg  gggggg  ggg                                                   ggggggggggggggggggggggggggg                                     g",
  "ggg     ggggggg               g   Q       gSSSgggSSSgggSSSg      Q       gggggggggggggggggggggggggggggggggggggg             p                  g",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"snowy_ground.png",
  "background image":"snowbg.png",
   "music":"icetheme.ogg",
          "decor":["pinetree1.png","pinetree2.png","snowbush.png"]}

level9 = {"num":9 ,"map":
 ["                                                                                                                                              ",
  "gl                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg                                                                                                                                              ",
  "gg  P                                                                                                                                            ",
  "gggggl                                                                                           f                                             ",
  "ggggggggl    c                                                                                                                                  ",
  "gggggggggg   c                                                                                                                                   ",
  "gggggggggg   c               g     Q                 8                        Q        g         g                                              ",
  "gggggggggg   c               gbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg    g                                                  ",
  "gggggggggg     c             gb                                                                                                                 ",
  "gggggggggg     c             gb                                                                                   g                             ",
  "ggggggggggggl  c            ggb                                                                                   g                             ",
  "gggggggggggggl  c                g  g  g   gg                                                                     g                             ",
  "ggggggggggggggg  c             SSSSSSSSSSSS ggg      a 8                                                          g                             ",
  "ggggggggggggggg  c             gggggggggggggggggggggggggggggggg   SgS  gggggggggggggggg    b  b  b b   b   b      g                             ",
  "ggggggggggggggg   c                                               ggg                                      b      gg                            ",
  "ggggggggggggggg    c                                                                                       b      gg                            ",
  "gggggggggggggggl                                                                            b   b   bb  bb b      gg                            ",
  "ggggggggggggggggl                    a8                    a8                    8a         b                     gg                            ",
  "gggggggggggggggggggl               gggggg                gggggg                ggggg        b                     gg                            ",
  "ggggggggggggggggggggl             gggggggg             ggggggggg              ggggggg       b                     gg                            ",
  "ggggggggggggggggggggggggl    Q   ggggggggggg   Q     ggggggggggggg     Q    ggggggggggg     b           T        hgg                            ",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"snowy_ground.png",
  "background image":"snowbg.png",
   "music":"icetheme.ogg",
          "decor":["pinetree1.png","pinetree2.png","snowbush.png"]}

level10 = {"num":10 ,"map":
 ["gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggg    c Tc  c  c  c  c  c  c  c  c  ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggg           T        T             ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggggggggggggggggggggggggggggggggg    g          W              g   ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "ggggggggg                                 gggggggggggggggggggggggggggg                                gggggggggggggggggggggggggggggggggggggggggg",
  "ggggggg       ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg                ggggggggggggggggggggggggggggggggggggggggggg",
  "gggggg      gggggggggggggggggggggggg                               M             gggg     c c          ggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggg          ggggggggggggggg                                               gggggggg    c                 g          T       ggggggggggggg",
  "gggggggggggggggggg                                                                gggggggg    c                 g                     gggggggggg",
  "gggggggggggggggggggggggggggggggggggg                   cccccc                  ggggggggggg     c                g                    ggggggggggg",
  "gggggggg                     gggggggg                                           gggggggggg                      gg     JJJJJ   h   gggggggggggg",
  "ggggg           ccccccc      ggggggggggggggg    a     gSSgSSSg    t             ggggggggggg               f     gggg    ccccccc       ggggggggggg",
  "ggggg   gggggggggggggggggggg ggggggggggggggggggggggggggggggggggggggggggggg              ggggg                   c  gg   ccccccc   h  gggggggggggg",
  "ggggggg           ggggggggggcgg            c   c            ggggggggggggggggggggggggggg  ggggggggg              gg     ccccccc       ggggggggggg",
  "gggggggggg ccccc   ggggggggg gg   gggggggggggggg     T            M                      ggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggg  ggggggggcgggg   c c   gggggg            c c        T          gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggg               ggggggggg ggggggggggg  gggggg                               ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggg P       ggggggggggggggg             ggggggg      t        W   t   gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"cave.png",
  "background image":"cavebg.png",
   "music":"cavetheme.ogg",
          "decor":["cavetree1.png","cavetree2.png","cavebush.png"] }

level11 = {"num":11 ,"map":
 ["gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gg         ggggggggggggg                                                                                                                      gg",
  "gg   P     gggggggg h    J                ccccccccccccccccc c  c   ccc cccccccccccc                                                           gg",
  "ggbbbbbbbbbgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggbb                                                      gg",
  "gg         ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg                                                        gg",
  "gg    J    ggggggg           gggggggggggggggggggggggggggggggggggggggggggggggggggggggggbbbbbb                                                  gg",
  "ggg       gggggggg               T            M      T         M              M      T        g                             J                 gg",
  "gggg    ggggggggggg                     T                                                                                                     gg",
  "ggggg  gggggggggggggh                                                                           g                                       f     gg",
  "gggg cc   gggggggggggggg                 p                                                          g                                         gg",
  "gg   cc     ggggggggggggggggg        ggggggg  gg  g  ggg g ggg g ggg g gg g  gg                                                               gg",
  "gg   cc        c  c c c cM          gggg                                     ggg                   ggg g  gg  ggggg  g gggg g g gg  g gggggggggg",
  "ggg  bb                          gggggg                                     gggg             g gg                                             gg",
  "ggSSSSSSSg          t     t    ggggggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSggggggg    W  ggSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSgg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"],
 "ground image":"cave.png",
  "background image":"cavebg.png",
   "music":"cavetheme.ogg",
          "decor":["cavetree1.png","cavetree2.png","cavebush.png"] }


level12 = {"num":12 ,"map":
 ["gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                        E       gg",
  "gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                                gg",
  "gg                   t  gggggggggggg",
  "gg               ggggggggggggggggggg",
  "gg  W    t     ggggggggggggggggggggg",
  "gggggggggggggbb                   gg",
  "ggggggggggg           J  JJ       gg",
  "gggggggggggggggggg              gggg",
  "gggggggggggggggggggggg        gggggg",
  "ggggggggggggggggggggggggggbbgggggggg",
  "ggS   SgS   SgS       SgS    SgS Sgg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "ggS SgS       SgS      SgS       Sgg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "ggS      SgS      SgS       SgS  Sgg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "gg                                gg",
  "ggbbgggggggggggggggggggggggggggggggg",
  "gg             M               M  gg",
  "ggbb                              gg",
  "gg                                gg",
  "ggbb                              gg",
  "gg    gSSgSSgSSgSSgSSgSSg         gg",
  "ggggggggggggggggggggggggggggggbbbbgg",
  "gg                                gg",
  "ggbbgggggggggggggggggggggggggggggggg",
  "gg                           gg   gg",
  "ggbb            J          gbggbgbgg",
  "gg                         g gg g gg",
  "ggbb                       gbggbgbgg",
  "gg         J               g    g gg",
  "gggggggggggggggggggggggggggggggggbgg",
  "ggM                    M          gg",
  "gg                               bgg",
  "gg                                gg",
  "gggggggggbbbbggggggggggggggggggggggg",
  "gg W                              gg",
  "ggggggggggggggggggggggggggggbbbbgggg",
  "gg W                              gg",
  "gggggggggggggggbbbbbgggggggggggggggg",
  "gg W                              gg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "gg W                              gg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "gg W                              gg",
  "ggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbgg",
  "ggl                               gg",
  "gggl                              gg",
  "gggggl      P           a     aa  gg",
  "gggggggggggggggggggggggggggggggggggg",
  "gggggggggggggggggggggggggggggggggggg"],
 "ground image":"cave.png",
  "background image":"cavebg.png",
   "music":"cavetheme.ogg",
          "decor":["cavetree1.png","cavetree2.png","cavebush.png"] }